### ISSUE TITLE
Reconsider using the System.* namespace

### ISSUE THREAD

**Issue by tuespetre** [deniszykov/commandline#1]
I found this repo because I've been toying around with Microsoft's own experimental `System.CommandLine` package, and in the last short period of time your repo's URL has started showing up on my tooltips when I hover over the dependency in project.json.

https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine
https://www.myget.org/gallery/dotnet-corefxlab

**Comment by deniszykov** [comment]
Thank you for informing. It was originally a bad idea to call package 'System.XXX'.
I renamed it to ConsoleApp.CommandLine since 'CommandLine' is taken.
