### ISSUE TITLE
How do I make it accept negative arguments?

### ISSUE THREAD

**Issue by shellinspector** [deniszykov/commandline#2]
Hello Denis,
It seems your application does not allow for negative numbers because "-" is used for other purposes. I need to do something like this:
"move --axes axis_x --position -1000" 
When it sees a minus it gets crazy. Otherwise a very nice library.

**Comment by deniszykov** [comment]
Hi! I made 3 changes in 54bf406545c52772af2ab916d2fe12c716955174 to address this issue. Special treatment for numbers will solve your current issue. Other two are fixing this issue in general cases. Docs are updated.

Fresh Nuget package is uploaded.
>Otherwise a very nice library.

Thanks!

**Comment by shellinspector** [comment]
Cпасибо, Денис.
