### ISSUE TITLE
No errors shown for unused parameters

### ISSUE THREAD

**Issue by belucha** [deniszykov/commandline#3]
First of all great idea!

In your sample program binding works for e.g.
`ConsoleApp.CommandLine.Example.exe math add --value1 1 --value2 3` 

but it also works for:

`ConsoleApp.CommandLine.Example.exe math add --value1 1 --value2 3 --whatever affe` 

And I never get to see the reason for binding failures, e.g.

`ConsoleApp.CommandLine.Example.exe math add --value1 1 --value2 text`

just shows the help screen.

I also have troubles, when binding to and method like:

```cs
        [Description("Adds numbers and print result.")]
        public static int S(string[] values = null, string a = "a", string b = "b")
        {
            Console.WriteLine($"values: {(values != null ? String.Join("/", values) : "--")}");
            Console.WriteLine($"a: {a}");
            Console.WriteLine($"b: {b}");
            return 0;
        }
```

`ConsoleApp.CommandLine.Example.exe math s  --values 1 2 3 31 --a 2 4`

Will call S with (a as an string array).

My conclusion is, that there is very little error and type/name checking on the parameters.

Are you planning to enhance that?

Regards Daniel

**Comment by deniszykov** [comment]
Hi Daniel!

Problem is in `math s --values 1 2 3 31 --a 2 <HERE> 4`
Parameter `a` is specified as an list of values, but declared as single value. If you expect 4 would be `b` parameter, it is not.
Because positional parameters was ended after first named parameter. 
Solution is to set name for parameter ‘b’ (actually single minus is working) `-a 2 -b 4`. 

P.S. I have also updated readme with description of lone `--` and `-` parameters.
 
Denis Zykov

**Comment by belucha** [comment]
Hi Denis,
your are right, I know that the arguments are incorrect, but I can't expect the user of the application to do everything right. So I would need some kind of error checking.

Daniel

**Comment by deniszykov** [comment]
I will add more detailed error message or special `CommandBindingExecption`. Also you could handle binding errors with ```CommandLine.UnhandledException```

**Comment by deniszykov** [comment]
I added better error support in 51b84f6447893829ed0cb2711d82523867143bdc. Not it will describe which parameter is bad and why.

Version is beta because parameters binding changes were made. I will test it and make release later.
