### ISSUE TITLE
.Net Core 2.1 ignores all commandline arguments

### ISSUE THREAD

**Issue by ghost** [deniszykov/commandline#6]
After upgrading my app to .Net Core 2.1 all arguments seem to be ignored.

Reproduce:

Upgrade a project from .Net Core 2.0 to 2.1.

Given two entry methods in Program.cs that I intend to call from the commandline:

```
static int Demo()
{
    return 0;
}

static int Demo(string path)
{
    return 0;
}
```

I was able to call them with .Net Core 2.0:

Call Demo():

> dotnet MyApp.dll Demo

Call Demo(string):

> dotnet MyApp.dll Demo Foo
> dotnet MyApp.dll Demo --path Foo

After upgrading to .Net Core 2.1 all these calls result in only Demo() being called, all parameters seem to be ignored.

I figured out that the issue is actually caused in the typeconvert library so I have created an [according issue there](https://github.com/deniszykov/typeconvert/issues/1).

The commandline project seems to silently ignore the exception thrown which is why the wrong method is called.

**Comment by deniszykov** [comment]
Hi @MarcStan. Thanks for investigating this problem. This saves me a lot of time.
It is not ignoring parameter, it can't convert passed values to required types (due error in TypeConvert) and continue to next method.

Fixed in [v.1.2.8](https://www.nuget.org/packages/ConsoleApp.CommandLine/1.2.8)

**Comment by ghost** [comment]
Thanks for the quick fix!
